CREATE TABLE [FHL].[Player]
(
	[Id] INT NOT NULL IDENTITY(1,1) CONSTRAINT [PK_Player] PRIMARY KEY, 
    
	[NHLId] INT NOT NULL
		CONSTRAINT [FK_FHLPlayer_NHLPlayer] FOREIGN KEY ([NHLId]) REFERENCES [NHL].[Player]([Id])
)
