CREATE TABLE [FHL].[Team]
(
	[Id] INT NOT NULL CONSTRAINT [PK_Team] PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	[LeagueId] INT NOT NULL

    CONSTRAINT [FK_Team_League] FOREIGN KEY ([LeagueId]) REFERENCES [FHL].[League]([Id])
)
